---
title: "240509602_P1"
author: "Stacia Tan Rui Shi (Student ID : 240509602)"
date: "2026-04-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#PART 1A
log_f <- function(x) {
  return(log(0.5) - abs(x))
} #to ensure we always use log

N <- 10000
s <- 1
x0 <- 0

samples <- numeric(N + 1)
samples[1] <- x0

for (i in 1:N) {
  x_prev <- samples[i]
  x_star <- rnorm(1, mean = x_prev, sd = s) #rnorm = random normal
  log_ratio <- log_f(x_star) - log_f(x_prev)
  u <- runif(1, min=0, max=1) 
  if (log(u) < log_ratio) {
    samples[i + 1] <- x_star  # Accept
  } else {
    samples[i + 1] <- x_prev  # Reject
  }
}
final_samples <- samples[-1]
sample_mean <- mean(final_samples)
sample_sd <- sd(final_samples)
#cat = print & sprintf = show returns and round to 4df 
cat(sprintf("Sample Mean: %.4f\n", sample_mean))
cat(sprintf("Sample Standard Deviation: %.4f\n", sample_sd))

hist(final_samples, freq = FALSE, breaks = 50, 
     col = "darkblue", border = "darkgray",
     main = "Random Walk Metropolis (N=10000, s=1)", 
     xlab = "x", ylab = "Density",
     xlim = c(-8, 8),
     ylim = c(0, 0.6))
     
lines(density(final_samples), col = "blue", lwd = 2)
x_range <- seq(-10, 10, length.out = 500)
true_f <- 0.5 * exp(-abs(x_range))
lines(x_range, true_f, col = "red", lty = 2, lwd = 2)
legend("topright", legend = c("Kernel Density Estimate", "Truef(x)"),
       col = c("blue", "red"), lty = c(1, 2), lwd = 2)
       
sample_mean <- mean(final_samples)
sample_sd <-sd(final_samples)
cat("Sample Mean:", sample_mean)
cat("Sample Standard Deviation:", sample_sd)
```       

```{r}
#PART 1B
#recall formula f(x) = 1/2exp
generate_chain <- function(N, s, x0) {
  x <- numeric(N +1)
  x[1] <- x0
  for (i in 1:N) {
  x_prev <- x[i]
  x_star <- rnorm(1, mean = x_prev, sd = s)
  log_ratio <- (log(0.5)- abs(x_star)) - (log(0.5) - abs(x_prev)) 
  u <- runif(1, min = 0, max = 1)
  if (log(u) < log_ratio) {
    x[i + 1] <- x_star
    } else {
      x[i + 1] <- x_prev
    }
  }
  return(x[-1])
}

#r estimate
calculate_R_est <- function(N, s, J, initial_values) {
   chains <- matrix(nrow = N, ncol = J)
   for (j in 1:J) {
     chains[, j] <- generate_chain(N, s, initial_values[j])
   }
   M_j <- colMeans(chains)
   V_j <- numeric(J)
   for (j in 1:J) {
     V_j[j] <- sum((chains[, j] - M_j[j])^2) / N
  }
  W <- mean(V_j)
  M <- mean(M_j)
  B <- sum((M_j - M)^2) / J
  R_est <- sqrt((B + W) / W)
  return(R_est)
}
N <- 2000
s_test <- 0.001
J <- 4
initial_values <- c(-2.0, -1.0, 1.0, 2.0)
R_est_value <- calculate_R_est(N, s_test, J, initial_values)
s_grid <- seq(0.001, 1.0, length.out = 50)
R_est_results <- numeric(length(s_grid))
for (i in 1:length(s_grid)) {
  R_est_results[i] <- calculate_R_est(N, s_grid[i], J, initial_values)
}
plot(s_grid, R_est_results, type = "b", pch = 16, col = "purple",
     xlab = "Step size (s)", ylab = "R-est Value",
     main = sprintf("R-est Values across different step sizes (s)\n(N=%d, J=%d)", N, J))
abline(h = 1.05, col = "red", lty = 2, lwd = 2)
legend("topright", legend = "Convergence Threshold (1.05)",
       col = "red", lty = 2, lwd = 2)
     
cat("R-est value for when s=0.001 is:", R_est_value)
results_table <- data.frame(StepSize = s_grid, REstimate = R_est_results)
print(results_table)
```